# Generated by Django 4.2.3 on 2023-07-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celebraties",
            name="id",
        ),
        migrations.AlterField(
            model_name="celebraties",
            name="name",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
