# Generated by Django 4.2.3 on 2023-07-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_celebraties_id_alter_celebraties_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="celebraties",
            name="discription",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
